apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox
spec:
  replicas: 1  
  selector:
    matchLabels:
      app: busybox-test
  template:
    metadata:
      labels:
        app: busybox-test
    spec:
      imagePullSecrets:
      - name: imagepull-docker
      containers:
      - name: busybox
        image: ramakrishna8254/week:v3
        imagePullPolicy: Always
        ports:
          - containerPort: 8085
---

apiVersion: v1
kind: Service
metadata:
  name: busybox-test
spec:
  ports:
  - port: 80
    targetPort: 8085
  selector:
    app: busybox-test
  type: LoadBalancer
